### PR TITLE
Adds support for rxjs6

### PR DESCRIPTION
**Pull request by paschalidi**
Adds support for rxjs version6. 

For the reason that `pipe` is not supported on rxjs v4 but it is supported on v6 `rx4Connect.js` is created to maintain v4.
The original `rxConnect.js` is being updated with the `pipe` operator to support rxjs v6.

### CODE REVIEW

**Comment by paschalidi** [comment]
@bsideup what is blocking you here? Please let me know how could I help you with that :)

**Comment by bsideup** [comment]
Hi @paschalidi,

The problem with this PR is the same as with #10. Please split it into smaller PRs, one change at a time.
I would suggest:
1) default to RxJS 5
2) Add RxJS 6 support
3) unify RxJS 5 and 6 by using the pipe operator in both. Please note that pipe operators appeared only in RxJS 5.5.

**Comment by paschalidi** [comment]
@bsideup gonna close this one for now. I dont have the capacity to work on this

**Comment by bsideup** [comment]
Ok.

**Comment by paschalidi** [comment]
I will reopen @bsideup when I will start working on that.

**Comment by bsideup** [comment]
Thanks. Although I suggest opening a new one, with 1 change at a time (see my previous comment)

**Comment by paschalidi** [comment]
Hey @bsideup agree it must be split.  Into smaller ones so that we can gracefully migrate. 
Can we please spent some time into reasoning this so that I can better understand the requirements?

> default to RxJS 5

means we would like to drop support of v4 completely on the next PR?

**Comment by bsideup** [comment]
I won't drop it, but make RxJS 5 the default, and provide an adapter for RxJS 4 (like we do atm with 5)

**Comment by paschalidi** [comment]
okay that makes absolutely sense. 
Thanks for taking the time to explain @bsideup will take care of this

**Comment by bsideup** [comment]
Thanks for working on it!

**Pull request closed without merging**
