### PR TITLE
Add adapters for rxjs 6 and rxjs 5.5

### PR DESCRIPTION
**Pull request by herman-rogers**
- Adding adapters that support rxjs 6 and newer versions of rxjs 5
- Added support for pipeable operators

### CODE REVIEW

**Comment by herman-rogers** [comment]
*Discussion* Over whether or not to remove rxjs 4 support. Basically, since we're using pipe (and that's the vision moving forward with rxjs) we can easily support rxjs 5 and 6 but 4 doesn't use this concept so the question is, do we provide a wrapper for when we use the pipe operator or drop it completely. I've left in 4 at the moment but have not yet integrated it until a decision was made

**Comment by bsideup** [comment]
Hi @herman-rogers!

Please ping me when you feel that the PR is ready for the review (I see "WIP" so I assume it is not yet, let me know otherwise :) )

**Comment by herman-rogers** [comment]
Ahh it's ready now to be reviewed now @bsideup - although we might want to discuss the rxjs 4 support issue. I'll remove the WIP in any case :)

**Comment by bsideup** [comment]
Hi @herman-rogers,

This PR is too big because it does more than 1 thing. I would really prefer to have it split into a few, one with RxJS 6 support and another one with RxJS 4 removal

**Pull request closed without merging**
